general {
#    disable_loading_bar = false
#    grace = 0
    hide_cursor = true
#    no_fade_in = false
#    no_fade_out = false
    ignore_empty_input = false
}

# Hintergrund
background {
    monitor =
    path = screenshot   # Verwendet aktuellen Desktop als Hintergrund
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

# Eingabefeld
input-field {
    monitor =
    size = 350, 50
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(33ccff)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Passwort oder Fingerabdruck...</i>
    hide_input = false
    rounding = 12
    check_color = rgb(00ff99)
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
#    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -20
    halign = center
    valign = center
#    pam_module = hyprlock
#    fingerprint = true
#    fingerprint_ready_message = Touch fingerprint sensor
#    fingerprint_present_message = Fingerprint recognized
}

# Uhrzeit
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    color = rgb(cdd6f4)
    font_size = 64
    font_family = Inter
    shadow_passes = 3
    shadow_size = 4

    position = 0, 200
    halign = center
    valign = center
}

# Datum
label {
    monitor =
    text = cmd[update:43200000] echo "<b> $(date +"%A, %d %B %Y") </b>"
    color = rgb(cdd6f4)
    font_size = 24
    font_family = Inter
    shadow_passes = 1
    shadow_size = 2

    position = 0, 140
    halign = center
    valign = center
}

# User-Label
label {
    monitor =
    text = $USER
    color = rgb(cdd6f4)
    font_size = 18
    font_family = Inter
    shadow_passes = 1
    shadow_size = 2

    position = 0, -100
    halign = center
    valign = center
}

# Keyboard Layout
label {
    monitor =
    text = $LAYOUT
    color = rgb(cdd6f4)
    font_size = 16
    font_family = Inter
    
    position = 30, 30
    halign = left
    valign = bottom
}

# Caps Lock Warnung
label {
    monitor =
    text = Caps Lock
    color = rgb(f38ba8)
    font_size = 16
    font_family = Inter
    
    position = 30, 70
    halign = left
    valign = bottom
}
