################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# Laptop display (scaled to 1.25x = effective 2048x1152)
monitor = eDP-1, 2560x1440@60, 0x0, 1.25,bitdepth,10

# Samsung Odyssey G80SD (4K display positioned to the right)
monitor = DP-5, 3840x2160@60.00Hz, 2048x0, 1.5
